version: '3.4'

services:
  ink-ink-frontend:
    image: arafat2025/ink-frontend:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000